### PR TITLE
Use WAL mode for the database

### LINKED ISSUE #15: Error Code SQLITE_LOCKED (6): Database Is Locked
This error occurs infrequently when using `express-session`

### PR DESCRIPTION
**Pull request by wmertens**
Fixes #15 

Untested, and it splits the database file into 3 files. Perhaps this should be optional?

### CODE REVIEW

**Comment by rawberg** [comment]
I agree this should be optional. is there a clean way to support this if a user wants to opt into WAL mode?

**Comment by wmertens** [comment]
Yes, only add the WAL command to the exec string if the user chose that
option.

**Comment by wmertens** [comment]
maybe something like

```js
this.db.exec((options.concurrentDb ? 'PRAGMA journal_mode = wal; ' : '') + 'CREATE ......'
```

**Comment by wmertens** [comment]
I added that option in the branch.

**Pull request merged**
